---
- hosts: webserver

  vars_files:
    - vars.yml

  pre_tasks:
    - name: 更新apt缓存
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: 重启Apache
      service: name=apache2 state=restarted

  tasks:
    - name: 安装用来管理ATP源的工具
      apt: "name={{ item }} state=present"
      with_items:
        - python-apt
        - python-pycurl

    - name: 添加包含有5.5版本PHP的ondrej源
      apt_repository: repo='ppa:ondrej/php5-5.6' update_cache=yes

    - name: 安装Apache，MySQL，PHP以及依赖关系
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - curl
        - sendmail
        - apache2
        - php5
        - php5-common
        - php5-mysql
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-dev
        - php5-mcrypt
        - php5-apcu
        - php-pear
        - python-mysqldb
        - mysql-server

    - name: 关闭防火墙（因为本项目仅供本地开发使用）
      service: name=ufw state=stopped

    - name: "启动Apache，MySQL"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: 启用Apache的rewrite模块(Drupal需要这个模块).
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: 在Apache中为Drupal添加virtualhost
      template:
        src: "templates/drupal.dev.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: 在sites-enabled目录中添加Drupal所需配置文件的符号链接
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart apache

    - name: 删除默认的virtualhost配置文件
      file:
        path: "/etc/apache2/sites-enabled/000-default"
        state: absent
      notify: restart apache

    - name: 开启PHP上传功能
      lineinfile:
        dest: "/etc/php5/apache2/conf.d/20-apcu.ini"
        regexp: "^apc.rfc1867"
        line: "apc.rfc1867 = 1"
        state: present
      notify: restart apache

    - name: 删除test数据库
      mysql_db: db=test state=absent

    - name: 为Drupal创建新库
      mysql_db: "db={{ domain }} state=present"

    - name: 下载Composer安装脚本
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: 运行Composer安装脚本
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: 将Composer放入/usr/local/bin目录中供全局使用
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: 从Github中下载Drush代码
      git:
        repo: https://github.com/drush-ops/drush.git
        dest: /opt/drush

    - name: 使用Composer安装Drush
      shell: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: 创建Drush命令的符号链接
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link

    - name: 下载Drupal代码到Apache的DocumentRoot目录中
      git:
        repo: http://git.drupal.org/project/drupal.git
        version: "{{ drupal_core_version }}"
        dest: "{{ drupal_core_path }}"

    - name: 使用Comoser安装Drupal的依赖关系
      shell: >
        /usr/local/bin/composer install
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php

    - name: 安装Drupal
      command: >
        drush si -y --site-name="{{ drupal_site_name }}"
        --account-name=admin
        --account-pass=admin
        --db-url=mysql://root@localhost/{{ domain }}
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php
      notify: restart apache

    - name: 为settings.php设置正确的权限
      file:
        path: "{{ drupal_core_path }}/sites/default/settings.php"
        mode: 0744

    - name: 开放files目录的所有权限
      file:
        path: "{{ drupal_core_path }}/sites/default/files"
        mode: 0777
        state: directory
        recurse: yes
